<?php

/**
 * Implements hook_ctools_plugin_directory()
 */
function dsv_bootstrap_panels_ctools_plugin_directory($module, $plugin) {
  if ($module == "panels" && $plugin == 'layouts') {
    return 'plugins/layouts';
  }
}

function dsv_bootstrap_panels_node_presave($node) {
	// Anslagstavlan has tid = 56
	// We enable commenting for this term
	if ($node->type == 'article') {
		if (count($node->field_news_category['und']) == 1 && $node->field_news_category['und'][0]['tid'] == 56) {
			$node->comment = 2;
		} else {
			$node->comment = 1;
		}
	}

	// Handle 'email this article'
	if (isset($node->field_massemail['und']) && $node->field_massemail['und'][0]['value'] == 1) {
		$node->subscriptions_notify = 1;
	} else {
		$node->subscriptions_notify = 0;
	}

	// Viktigt and Anslagstavlan are always emailed
	if (isset($node->field_news_category) and ($node->field_news_category['und'][0]['tid'] == 54 || $node->field_news_category['und'][0]['tid'] == 56)) {
		$node->subscriptions_notify = 1;
	}

	// Calendat items are always emailed
	if ($node->type == 'calendar_item') {
		$node->subscriptions_notify = 1;
	}
}