<?php

/**
 * Implements hook_ctools_plugin_directory()
 */
function dsv_bootstrap_panels_ctools_plugin_directory($module, $plugin) {
  if ($module == "panels" && $plugin == 'layouts') {
    return 'plugins/layouts';
  }
}

function dsv_bootstrap_panels_hook_form_alter(&$form, &$form_state, $form_id) {
	global $user;
	if (!isset($user->roles[3])) {
		unset($form['field_already_emailed']);
	}
}

function dsv_bootstrap_panels_form_article_node_form_alter(&$form, &$form_state, $form_id) {
	foreach ($form['field_news_category']['und']['#options'] as $key => $term) {
		if ($term == 'Anslagstavlan') {
			$form['field_news_category']['und']['#options'][$key] .= ' ('.t('this category will not be emailed').')';
		}
	}
}